language: ruby
cache:
  - apt
  - bundler
bundler_args: --without production --binstubs
env:
  - RAILS_ENV=test CODECLIMATE_REPO_TOKEN=12c0eb766b5b8906cfa609dabe9d41070f4bf83242dd6aa0a3b68a24516f6589
addons:
  postgresql: "9.3"
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database dev_kg_test;' -U postgres
script:
  - bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec/
